[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyrepak"
version = "0.0.5"
authors = [
  { name = "stas96111", email = "stas96111@gmail.com" },
]
description = "PyRepak is a binding of repak libraries for working with Unreal Engine .pak files"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

[tool.setuptools]
license-files = []

[project.urls]
Homepage = "https://github.com/stas96111/pyrepak"

[tool.setuptools.package-data]
pyrepak = ["*.dll"]  # Include all DLLs in the package